all: superb confpr badino

superb: superb.c testlib
	cc -o superb -O superb.c testlib

confpr: confpr.c testlib
	cc -o confpr -O confpr.c testlib

badino:	badino.c testlib
	cc -o badino -O badino.c testlib
